FROM postgres:16-bullseye

# Install required packages
RUN apt-get update \
    && apt-get -y install netcat git build-essential postgresql-server-dev-16 pgagent iputils-ping telnet \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set up user
RUN userdel postgres
RUN groupadd -g 1000 postgres
RUN useradd -m -u 1000 -g 1000 postgres

ENV HOME=/home/db

# Use default PGDATA; let Docker mount volume to /var/lib/postgresql/data
# Copy SQL init scripts
COPY db/postgres/init/000_create_schema.sql /docker-entrypoint-initdb.d/000_create_schema.sql
COPY db/postgres/init/001_create_tables.sql /docker-entrypoint-initdb.d/001_create_tables.sql
COPY db/postgres/init/002_load_sample_data.sql /docker-entrypoint-initdb.d/002_load_sample_data.sql
COPY db/postgres/init/003_create_access_control.sql /docker-entrypoint-initdb.d/003_create_access_control.sql
COPY db/postgres/init/004_link_user_to_access_control.sql /docker-entrypoint-initdb.d/004_link_user_to_access_control.sql
COPY db/postgres/init/005_create_medals_system.sql /docker-entrypoint-initdb.d/005_create_medals_system.sql
COPY db/postgres/init/006_create_medals_system.sql /docker-entrypoint-initdb.d/006_create_medals_system.sql
COPY db/postgres/init/007_create_tournament_invitation_system.sql /docker-entrypoint-initdb.d/007_create_tournament_invitation_system.sql
COPY db/postgres/init/008_create_reports_system.sql /docker-entrypoint-initdb.d/008_create_reports_system.sql
COPY db/postgres/init/009_add_report_views.sql /docker-entrypoint-initdb.d/009_add_report_views.sql

# Let base image entrypoint handle startup
CMD ["postgres"]
