version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: badminton_hobby
      POSTGRES_USER: badminton_user
      POSTGRES_PASSWORD: simple_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://badminton_user:simple_password_123@db:5432/badminton_hobby
      SECRET_KEY: hobby-secret-key-for-friends-2024
      ENVIRONMENT: production
      CORS_ORIGINS: https://yourdomain.com
    restart: unless-stopped

volumes:
  postgres_data:
